### ISSUE TITLE
Create the profile page for the EchoLink app

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/EchoLink#20]
The profile page of the EchoLink app should have the basic details of the user along with some statistics like the total time played and number of links created to date. The UI should be minimalist and the page will be opened from the hamburger menu. Feel free to experiment with any kind of data you want to add/ any design you like.

**Happy Coding**

**Comment by tanush077** [comment]
I can take up this issue

**Comment by JuxtaRYCT** [comment]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-10-27 at 16 28 00](https://github.com/ACM-VIT/EchoLink/assets/116808459/3b41e647-7eca-467c-8021-025256b6cb00)

The profile page was designed and functionality was added in the app. The Pull Request was merged on 27 October, 2023

Yash Raj Singh
2023
