### ISSUE TITLE
Create the sign up page for the app

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/EchoLink#47]
Create the signup page for the app, include basic details such as Name, Age, email address/signup with google, and create password.

**Comment by rghvsh** [comment]
Hey! @JuxtaRYCT I'd like to work on this issue

**Comment by Abh1noob** [comment]
me

**Comment by JuxtaRYCT** [comment]
The signup page was created by Abhinav Ganeshan and the PR was merged.

Yash Raj Singh,
2023
