### ISSUE TITLE
Add a logo for the EchoLink application

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/EchoLink#5]
**Add a logo for the EchoLink application**

**Comment by eshita241** [comment]
..

**Comment by JuxtaRYCT** [comment]
<img width="75" alt="Screenshot 2023-10-27 at 4 29 25 PM" src="https://github.com/ACM-VIT/EchoLink/assets/116808459/37985e07-51b1-4636-8621-9ccd2e6e043e">

The logo was designed and added in the app.
