### ISSUE TITLE
Create Splash Screen

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/EchoLink#6]
Create a Splash Screen for the EchoLink application. Use your imagination and creativity to create a splash screen for the EchoLink application. Please follow any tutorial/ documentation of your choice to create the splash screen. The Splash Screen should be dynamic and should not be hard-coded for a specific time. Happy Coding. :)

**Comment by tanush077** [comment]
I would like to take this issue

**Comment by aastikn** [comment]
I would like to take this issue

**Comment by JuxtaRYCT** [comment]
The splash screen was created by Aastik Narang and the PR has been merged.

Yash Raj Singh, 2023
